# Generated by Django 6.0.4 on 2026-04-15 04:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('new', 'Yangi'), ('in_progress', 'Jarayonda'), ('completed', 'Bajarildi'), ('blocked', 'Bloklangan'), ('cancelled', 'Bekor qilindi'), ('overdue', "Muddati o'tgan")], max_length=20, verbose_name='Eski holat')),
                ('new_status', models.CharField(choices=[('new', 'Yangi'), ('in_progress', 'Jarayonda'), ('completed', 'Bajarildi'), ('blocked', 'Bloklangan'), ('cancelled', 'Bekor qilindi'), ('overdue', "Muddati o'tgan")], max_length=20, verbose_name='Yangi holat')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Izoh')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Holat tarixi',
                'verbose_name_plural': 'Holat tarixlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('instructions', models.TextField(verbose_name="Ko'rsatmalar")),
                ('priority', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori'), ('urgent', 'Shoshilinch')], default='medium', max_length=20, verbose_name='Ustuvorlik')),
                ('task_type', models.CharField(choices=[('one_time', 'Bir martalik'), ('recurring', 'Takrorlanuvchi')], default='one_time', max_length=20, verbose_name='Vazifa turi')),
                ('recurrence_type', models.CharField(choices=[('none', "Yo'q"), ('daily', 'Har kuni'), ('weekly', 'Har hafta'), ('monthly', 'Har oy'), ('yearly', 'Har yil')], default='none', max_length=20, verbose_name='Takrorlanish turi')),
                ('report_frequency', models.CharField(choices=[('none', "Yo'q"), ('daily', 'Kunlik'), ('weekly', 'Haftalik'), ('monthly', 'Oylik'), ('yearly', 'Yillik')], default='none', max_length=20, verbose_name='Hisobot chastotasi')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('estimated_duration', models.PositiveIntegerField(blank=True, help_text='Soatlarda', null=True, verbose_name='Taxminiy davomiyligi')),
                ('attachments_allowed', models.BooleanField(default=True, verbose_name='Ilova yuklashga ruxsat')),
                ('report_required', models.BooleanField(default=True, verbose_name='Hisobot majburiy')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Vazifa shabloni',
                'verbose_name_plural': 'Vazifa shablonlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('instructions', models.TextField(verbose_name="Ko'rsatmalar")),
                ('priority', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori'), ('urgent', 'Shoshilinch')], db_index=True, default='medium', max_length=20, verbose_name='Ustuvorlik')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('in_progress', 'Jarayonda'), ('completed', 'Bajarildi'), ('blocked', 'Bloklangan'), ('cancelled', 'Bekor qilindi'), ('overdue', "Muddati o'tgan")], db_index=True, default='new', max_length=20, verbose_name='Holat')),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Tugash vaqti')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish vaqti')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bajarilish vaqti')),
                ('is_overdue', models.BooleanField(db_index=True, default=False, verbose_name="Muddati o'tgan")),
                ('report_required', models.BooleanField(default=True, verbose_name='Hisobot majburiy')),
                ('report_frequency', models.CharField(choices=[('none', "Yo'q"), ('daily', 'Kunlik'), ('weekly', 'Haftalik'), ('monthly', 'Oylik'), ('yearly', 'Yillik')], default='none', max_length=20, verbose_name='Hisobot chastotasi')),
                ('attachments_allowed', models.BooleanField(default=True, verbose_name='Ilova yuklashga ruxsat')),
                ('current_period_start', models.DateTimeField(blank=True, null=True, verbose_name='Joriy davr boshi')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='Joriy davr oxiri')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('assigned_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_instances', to='departments.department', verbose_name="Bo'lim")),
            ],
            options={
                'verbose_name': 'Vazifa',
                'verbose_name_plural': 'Vazifalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
