# Generated by Django 6.0.4 on 2026-04-15 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_task_instances', to=settings.AUTH_USER_MODEL, verbose_name='Xodim'),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_task_instances', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi'),
        ),
        migrations.AddField(
            model_name='taskstatushistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to=settings.AUTH_USER_MODEL, verbose_name="O'zgartirgan"),
        ),
        migrations.AddField(
            model_name='taskstatushistory',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='tasks.taskinstance', verbose_name='Vazifa'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='assigned_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_templates', to='departments.department', verbose_name="Bo'lim"),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_templates', to=settings.AUTH_USER_MODEL, verbose_name='Xodim'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi'),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='tasks.tasktemplate', verbose_name='Shablon'),
        ),
        migrations.AddIndex(
            model_name='taskstatushistory',
            index=models.Index(fields=['task', 'created_at'], name='tasks_tasks_task_id_565eb3_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktemplate',
            index=models.Index(fields=['task_type', 'is_active'], name='tasks_taskt_task_ty_064f23_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktemplate',
            index=models.Index(fields=['recurrence_type', 'is_active'], name='tasks_taskt_recurre_65db3e_idx'),
        ),
        migrations.AddIndex(
            model_name='taskinstance',
            index=models.Index(fields=['status', 'is_overdue'], name='tasks_taski_status_d87438_idx'),
        ),
        migrations.AddIndex(
            model_name='taskinstance',
            index=models.Index(fields=['assigned_user', 'status'], name='tasks_taski_assigne_16dd0a_idx'),
        ),
        migrations.AddIndex(
            model_name='taskinstance',
            index=models.Index(fields=['assigned_department', 'status'], name='tasks_taski_assigne_936dd8_idx'),
        ),
        migrations.AddIndex(
            model_name='taskinstance',
            index=models.Index(fields=['due_at', 'status'], name='tasks_taski_due_at_2201ba_idx'),
        ),
    ]
