# Generated by Django 5.0.6 on 2026-04-15 20:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(choices=[('coordinator', 'Coordinator Agent'), ('operations', 'Operations Agent'), ('customer_support', 'Customer Support Agent'), ('sales', 'Sales Agent'), ('marketing', 'Marketing Agent'), ('analytics', 'Analytics Agent')], max_length=50)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('system_prompt', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agent Prompt Template',
                'ordering': ['-version'],
                'unique_together': {('agent_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='AgentConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(choices=[('coordinator', 'Coordinator Agent'), ('operations', 'Operations Agent'), ('customer_support', 'Customer Support Agent'), ('sales', 'Sales Agent'), ('marketing', 'Marketing Agent'), ('analytics', 'Analytics Agent')], max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('autonomy_level', models.FloatField(default=0.3)),
                ('custom_instructions', models.TextField(blank=True, help_text='Additional instructions for this agent specific to your company.')),
                ('daily_token_budget', models.PositiveIntegerField(blank=True, null=True)),
                ('schedule_config', models.JSONField(default=dict, help_text='e.g., {"daily_briefing_hour": 8, "timezone": "Asia/Tashkent"}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_configs', to='tenants.company')),
            ],
            options={
                'verbose_name': 'Agent Configuration',
                'unique_together': {('company', 'agent_type')},
            },
        ),
        migrations.CreateModel(
            name='AgentExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(choices=[('coordinator', 'Coordinator Agent'), ('operations', 'Operations Agent'), ('customer_support', 'Customer Support Agent'), ('sales', 'Sales Agent'), ('marketing', 'Marketing Agent'), ('analytics', 'Analytics Agent')], max_length=50)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='started', max_length=30)),
                ('trigger_source', models.CharField(choices=[('scheduled', 'Scheduled (Celery Beat)'), ('user_command', 'User Command'), ('telegram', 'Telegram Command'), ('workflow', 'Workflow Trigger'), ('system_event', 'System Event'), ('agent_delegation', 'Agent Delegation')], max_length=30)),
                ('task_description', models.TextField()),
                ('input_context', models.JSONField(default=dict)),
                ('llm_response', models.TextField(blank=True)),
                ('parsed_output', models.JSONField(default=dict)),
                ('actions_taken', models.JSONField(default=list)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_logs', to='tenants.company')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Execution Log',
                'verbose_name_plural': 'Agent Execution Logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['company', 'agent_type', 'status'], name='agents_agen_company_6e722f_idx'), models.Index(fields=['company', 'started_at'], name='agents_agen_company_2a66ca_idx')],
            },
        ),
    ]
