# Generated by Django 5.0.6 on 2026-04-15 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfiguration',
            name='parent_agent',
            field=models.ForeignKey(blank=True, help_text='The supervising agent that can delegate tasks to this agent. None = top-level.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_agents', to='agents.agentconfiguration'),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='system_prompt',
            field=models.TextField(blank=True, help_text='Full system prompt for this agent. Leave blank to use the platform default.'),
        ),
        migrations.AlterField(
            model_name='agentconfiguration',
            name='custom_instructions',
            field=models.TextField(blank=True, help_text='Extra instructions specific to your company, appended after the system prompt.'),
        ),
    ]
