# Generated by Django 5.0.6 on 2026-04-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentconfiguration_parent_agent_and_more'),
        ('organizations', '0002_head_office_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfiguration',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Departments this agent monitors. Empty = monitors all departments.', related_name='agents', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='monitor_chats',
            field=models.BooleanField(default=False, help_text='If enabled, agent analyzes chat messages in linked department rooms.'),
        ),
    ]
