# Generated by Django 5.0.6 on 2026-04-15 20:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(choices=[('coordinator', 'Coordinator Agent'), ('operations', 'Operations Agent'), ('customer_support', 'Customer Support Agent'), ('sales', 'Sales Agent'), ('marketing', 'Marketing Agent'), ('analytics', 'Analytics Agent')], max_length=50)),
                ('action_category', models.CharField(choices=[('task_management', 'Task Management'), ('communication', 'Communication'), ('data_change', 'Data Change'), ('external_action', 'External Action'), ('report_generation', 'Report Generation'), ('workflow_execution', 'Workflow Execution')], max_length=50)),
                ('action_type', models.CharField(max_length=100)),
                ('action_payload', models.JSONField(help_text='The exact data that will be used to execute the action upon approval.')),
                ('title', models.CharField(max_length=500)),
                ('reasoning', models.TextField(help_text="AI's explanation of why this action is recommended.")),
                ('confidence_score', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('auto_approved', 'Auto-Approved')], default='pending', max_length=20)),
                ('decision_comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('telegram_message_id', models.CharField(blank=True, max_length=100)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='tenants.company')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('execution_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_request', to='agents.agentexecutionlog')),
            ],
            options={
                'verbose_name': 'Approval Request',
                'verbose_name_plural': 'Approval Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='approvals_a_company_e8e537_idx'), models.Index(fields=['company', 'expires_at'], name='approvals_a_company_d2ab13_idx')],
            },
        ),
    ]
