# Generated by Django 6.0.4 on 2026-04-15 04:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('telegram_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Foydalanuvchi nomi')),
                ('full_name', models.CharField(blank=True, default='', max_length=255, verbose_name="To'liq ism")),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefon raqam')),
                ('role', models.CharField(blank=True, choices=[('boss', 'Boshliq'), ('head', "Bo'lim boshlig'i"), ('employee', 'Ishchi')], db_index=True, max_length=20, null=True, verbose_name='Rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Admin xodim')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='departments.department', verbose_name="Bo'lim")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'indexes': [models.Index(fields=['telegram_id'], name='users_user_telegra_b51e4c_idx'), models.Index(fields=['role'], name='users_user_role_36d76d_idx'), models.Index(fields=['department'], name='users_user_departm_7e3aa1_idx')],
            },
        ),
    ]
