# Generated by Django 5.0.6 on 2026-04-16 11:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('bitrix24', 'Bitrix24'), ('amocrm', 'AmoCRM'), ('odoo', 'Odoo ERP'), ('1c', '1C:Enterprise'), ('generic', 'Generic Webhook')], default='generic', max_length=20)),
                ('sync_direction', models.CharField(choices=[('import', 'Import only (CRM → AIManager)'), ('export', 'Export only (AIManager → CRM)'), ('both', 'Bidirectional')], default='both', max_length=10)),
                ('api_url', models.CharField(blank=True, help_text='Base API URL of the CRM/ERP', max_length=500)),
                ('api_key', models.CharField(blank=True, help_text='API key or token', max_length=500)),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret to validate incoming webhooks', max_length=255)),
                ('config', models.JSONField(default=dict, help_text='Type-specific configuration. Examples:\nBitrix24: {"portal_url": "...", "user_id": ...}\nOdoo:     {"db": "mydb", "uid": 1}\nGeneric:  {"task_create_endpoint": "/tasks", "task_update_endpoint": "/tasks/{id}"}')),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='tenants.company')),
            ],
            options={
                'verbose_name': 'External Integration',
                'verbose_name_plural': 'External Integrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound (CRM → AIManager)'), ('outbound', 'Outbound (AIManager → CRM)')], max_length=10)),
                ('result', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='success', max_length=10)),
                ('payload', models.JSONField(default=dict)),
                ('response', models.JSONField(default=dict)),
                ('records_in', models.PositiveIntegerField(default=0, help_text='Records received / processed')),
                ('records_out', models.PositiveIntegerField(default=0, help_text='Records pushed to external system')),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='integrations.externalintegration')),
            ],
            options={
                'verbose_name': 'Integration Sync Log',
                'ordering': ['-created_at'],
            },
        ),
    ]
