# Generated by Django 5.0.6 on 2026-04-15 20:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('industry', models.CharField(choices=[('it_software', 'IT / Software'), ('marketing_agency', 'Marketing Agency'), ('ecommerce', 'E-Commerce'), ('consulting', 'Consulting'), ('saas', 'SaaS'), ('digital_services', 'Digital Services'), ('other', 'Other')], default='other', max_length=50)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('website', models.URLField(blank=True)),
                ('employee_count', models.PositiveIntegerField(default=1)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('agent_autonomy_level', models.FloatField(default=0.3, help_text='0.0 = full human approval required, 1.0 = full autonomy')),
                ('daily_token_budget', models.PositiveIntegerField(default=100000, help_text='Max OpenAI tokens per day across all agents')),
                ('tokens_used_today', models.PositiveIntegerField(default=0)),
                ('tokens_reset_at', models.DateTimeField(blank=True, null=True)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
    ]
