# Generated by Django 5.0.6 on 2026-04-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='author_display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Telegram group/channel chat ID to bridge with this room (e.g. -100123456789)', max_length=100, null=True),
        ),
    ]
