# Generated by Django 6.0.4 on 2026-04-15 04:45

import apps.reports.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Matn')),
                ('status', models.CharField(choices=[('submitted', 'Yuborildi'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], db_index=True, default='submitted', max_length=20, verbose_name='Holat')),
                ('manager_comment', models.TextField(blank=True, null=True, verbose_name='Menejer izohi')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yuborilgan vaqt')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name="Ko'rib chiqilgan vaqt")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Hisobot',
                'verbose_name_plural': 'Hisobotlar',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.reports.models.report_upload_path, verbose_name='Fayl')),
                ('file_type', models.CharField(choices=[('file', 'Fayl'), ('image', 'Rasm'), ('video', 'Video')], max_length=10, verbose_name='Fayl turi')),
                ('original_name', models.CharField(max_length=255, verbose_name='Asl nomi')),
                ('telegram_file_id', models.CharField(blank=True, default='', max_length=500, verbose_name='Telegram fayl ID')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yuklangan vaqt')),
            ],
            options={
                'verbose_name': 'Hisobot ilovasi',
                'verbose_name_plural': 'Hisobot ilovalari',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
