# Generated by Django 5.0.6 on 2026-04-16 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_head_office_type'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='department',
            name='unique_dept_name_per_parent',
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('company', 'name', 'parent')},
        ),
    ]
