# Generated by Django 6.0.4 on 2026-04-15 04:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_assigned', 'Vazifa tayinlandi'), ('task_reminder', 'Vazifa eslatmasi'), ('task_overdue', "Muddati o'tgan vazifa"), ('task_status_changed', "Holat o'zgartirildi"), ('report_submitted', 'Hisobot yuborildi'), ('report_accepted', 'Hisobot qabul qilindi'), ('report_rejected', 'Hisobot rad etildi'), ('report_overdue', "Hisobot muddati o'tdi"), ('recurring_task_created', 'Takrorlanuvchi vazifa yaratildi'), ('department_summary', "Bo'lim xulosasi")], db_index=True, max_length=50, verbose_name='Bildirishnoma turi')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('is_sent', models.BooleanField(db_index=True, default=False, verbose_name='Yuborildi')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan vaqt')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Xato xabari')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Bildirishnoma logi',
                'verbose_name_plural': 'Bildirishnoma loglari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Update ID')),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Qayta ishlangan')),
                ('raw_json', models.TextField(blank=True, default='', verbose_name='Raw JSON')),
            ],
            options={
                'verbose_name': 'Telegram update logi',
                'verbose_name_plural': 'Telegram update loglari',
                'ordering': ['-processed_at'],
            },
        ),
    ]
